In [1]:
import pandas as pd
import sqlite3

In [2]:
con = sqlite3.connect('weather_2012.sqlite')

In [4]:
df = pd.read_sql('SELECT * from weather_2012 LIMIT 3', con)
df

   id            date_time  temp
0   1  2012-01-01 00:00:00  -1.8
1   2  2012-01-01 01:00:00  -1.8
2   3  2012-01-01 02:00:00  -1.8

In [5]:
df = pd.read_sql("SELECT * from weather_2012 LIMIT 3", con, index_col='id')
df

              date_time  temp
id
1   2012-01-01 00:00:00  -1.8
2   2012-01-01 01:00:00  -1.8
3   2012-01-01 02:00:00  -1.8

In [6]:
weather_df = pd.read_csv('weather_2012.csv')
con = sqlite3.connect('test_db.sqlite')
con.execute('DROP TABLE IF EXISTS weather_2012')
weather_df.to_sql('weather_2012', con)

8784

In [7]:
df = pd.read_sql('SELECT * from weather_2012 LIMIT 3', con)
df

,index,Date/Time (LST),Longitude (x),Latitude (y),Station Name,Climate ID,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,0,2012-01-01 00:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1,2012-01-01 01:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2,2012-01-01 02:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"

In [8]:
df = pd.read_sql('SELECT * from weather_2012 ORDER BY Weather LIMIT 3', con)
df

,index,Date/Time (LST),Longitude (x),Latitude (y),Station Name,Climate ID,Temp (°C),Dew Point Temp (°C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,67,2012-01-03 19:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-16.9,-24.8,50,24,25.0,101.74,Clear
1,114,2012-01-05 18:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-7.1,-14.4,56,11,25.0,100.71,Clear
2,115,2012-01-05 19:00:00,-73.75,45.47,MONTREAL/PIERRE ELLIOTT TRUDEAU INTL A,7025250,-9.2,-15.4,61,7,25.0,100.80,Clear